package http

import (
	"encoding/json"
	"log/slog"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	_ "github.com/namcuongq/order-service/docs" // docs generated by Swag CLI
	"github.com/namcuongq/order-service/internal/application/command"
	"github.com/namcuongq/order-service/internal/application/dto"
	"github.com/namcuongq/order-service/internal/application/query"
)

// Handler holds all HTTP handlers and their dependencies.
type Handler struct {
	createOrder  *command.CreateOrderHandler
	addItem      *command.AddItemHandler
	confirmOrder *command.ConfirmOrderHandler
	getOrder     *query.GetOrderHandler
	listOrders   *query.ListOrdersHandler
	validator    *RequestValidator
	logger       *slog.Logger
}

func NewHandler(
	createOrder *command.CreateOrderHandler,
	addItem *command.AddItemHandler,
	confirmOrder *command.ConfirmOrderHandler,
	getOrder *query.GetOrderHandler,
	listOrders *query.ListOrdersHandler,
	logger *slog.Logger,
) *Handler {
	return &Handler{
		createOrder:  createOrder,
		addItem:      addItem,
		confirmOrder: confirmOrder,
		getOrder:     getOrder,
		listOrders:   listOrders,
		validator:    NewRequestValidator(),
		logger:       logger,
	}
}

// RegisterRoutes sets up chi routes.
func (h *Handler) RegisterRoutes(r chi.Router) {
	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), //The url pointing to API definition
	))

	r.Route("/orders", func(r chi.Router) {
		r.Post("/", h.HandleCreateOrder)
		r.Get("/", h.HandleListOrders)
		r.Route("/{orderID}", func(r chi.Router) {
			r.Get("/", h.HandleGetOrder)
			r.Post("/items", h.HandleAddItem)
			r.Post("/confirm", h.HandleConfirmOrder)
		})
	})
}

// @Summary Create a new order
// @Description Create an order for a given customer
// @Tags orders
// @Accept json
// @Produce json
// @Param request body dto.CreateOrderRequest true "Create Order Request"
// @Success 201 {object} dto.CreateOrderResult
// @Failure 400 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /orders [post]
func (h *Handler) HandleCreateOrder(w http.ResponseWriter, r *http.Request) {
	var req dto.CreateOrderRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, r, http.StatusBadRequest, "INVALID_REQUEST", "Invalid JSON body", nil)
		return
	}

	if errs := h.validator.Validate(req); errs != nil {
		writeError(w, r, http.StatusBadRequest, "VALIDATION_ERROR", "Request validation failed", errs)
		return
	}

	orderID, err := h.createOrder.Handle(r.Context(), command.CreateOrder{
		CustomerID: req.CustomerID,
	})
	if err != nil {
		mapAndWriteError(w, r, err)
		return
	}

	writeJSON(w, http.StatusCreated, dto.CreateOrderResult{OrderID: orderID})
}

// @Summary Add an item to an order
// @Description Add a new product to an existing DRAFT order
// @Tags orders
// @Accept json
// @Produce json
// @Param orderID path string true "Order ID"
// @Param request body dto.AddItemRequest true "Add Item Request"
// @Success 200 {object} map[string]string
// @Failure 400 {object} dto.ErrorResponse
// @Failure 404 {object} dto.ErrorResponse
// @Failure 409 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /orders/{orderID}/items [post]
func (h *Handler) HandleAddItem(w http.ResponseWriter, r *http.Request) {
	orderID := chi.URLParam(r, "orderID")

	var req dto.AddItemRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, r, http.StatusBadRequest, "INVALID_REQUEST", "Invalid JSON body", nil)
		return
	}

	if errs := h.validator.Validate(req); errs != nil {
		writeError(w, r, http.StatusBadRequest, "VALIDATION_ERROR", "Request validation failed", errs)
		return
	}

	err := h.addItem.Handle(r.Context(), command.AddItemToOrder{
		OrderID:     orderID,
		ProductID:   req.ProductID,
		ProductName: req.ProductName,
		Quantity:    req.Quantity,
		UnitPrice:   req.UnitPrice,
	})
	if err != nil {
		mapAndWriteError(w, r, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]string{"message": "item added"})
}

// @Summary Confirm an order
// @Description Transition order status from DRAFT to CONFIRMED
// @Tags orders
// @Accept json
// @Produce json
// @Param orderID path string true "Order ID"
// @Success 200 {object} map[string]string
// @Failure 400 {object} dto.ErrorResponse
// @Failure 404 {object} dto.ErrorResponse
// @Failure 409 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /orders/{orderID}/confirm [post]
func (h *Handler) HandleConfirmOrder(w http.ResponseWriter, r *http.Request) {
	orderID := chi.URLParam(r, "orderID")

	err := h.confirmOrder.Handle(r.Context(), command.ConfirmOrder{
		OrderID: orderID,
	})
	if err != nil {
		mapAndWriteError(w, r, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]string{"message": "order confirmed"})
}

// @Summary Get order details
// @Description Fetch an order by its ID from the read model
// @Tags orders
// @Accept json
// @Produce json
// @Param orderID path string true "Order ID"
// @Success 200 {object} dto.OrderResponse
// @Failure 404 {object} dto.ErrorResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /orders/{orderID} [get]
func (h *Handler) HandleGetOrder(w http.ResponseWriter, r *http.Request) {
	orderID := chi.URLParam(r, "orderID")

	result, err := h.getOrder.Handle(r.Context(), query.GetOrderByID{
		OrderID: orderID,
	})
	if err != nil {
		mapAndWriteError(w, r, err)
		return
	}

	writeJSON(w, http.StatusOK, result)
}

// @Summary List orders
// @Description Get a paginated list of orders, optionally filtered
// @Tags orders
// @Accept json
// @Produce json
// @Param status query string false "Filter by order status"
// @Param customer_id query string false "Filter by customer ID"
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(20)
// @Param sort query string false "Sort field (created_at, total_amount)"
// @Param dir query string false "Sort direction (asc, desc)"
// @Success 200 {object} dto.PaginatedOrdersResponse
// @Failure 500 {object} dto.ErrorResponse
// @Router /orders [get]
func (h *Handler) HandleListOrders(w http.ResponseWriter, r *http.Request) {
	q := query.ListOrders{
		SortBy:  r.URL.Query().Get("sort"),
		SortDir: r.URL.Query().Get("dir"),
		Page:    1,
		PageSize: 20,
	}

	if v := r.URL.Query().Get("status"); v != "" {
		q.Status = &v
	}
	if v := r.URL.Query().Get("customer_id"); v != "" {
		q.CustomerID = &v
	}
	if v := r.URL.Query().Get("page"); v != "" {
		if p, err := strconv.Atoi(v); err == nil && p > 0 {
			q.Page = p
		}
	}
	if v := r.URL.Query().Get("size"); v != "" {
		if s, err := strconv.Atoi(v); err == nil && s > 0 {
			q.PageSize = s
		}
	}

	result, err := h.listOrders.Handle(r.Context(), q)
	if err != nil {
		mapAndWriteError(w, r, err)
		return
	}

	writeJSON(w, http.StatusOK, result)
}

func writeJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(data)
}

